# Swiss Waste Recycling Chatbot - Open Source Configuration
# Generated by setup script

# Default model for the chatbot
DEFAULT_MODEL = "qwen2.5:7b-instruct"

# Ollama configuration
OLLAMA_URL = "http://localhost:11434"

# Model paths
MODEL_PATH = "../models/baseline/finetuned_model.pth"

# Available models
AVAILABLE_MODELS = ['qwen2.5:7b-instruct', 'mistral:7b-instruct', 'qwen2.5:3b-instruct']

# System settings
DEVICE = "auto"  # auto, cpu, cuda
DEFAULT_LANGUAGE = "de"  # de, en

print("Configuration saved!")
